### ISSUE TITLE
UX Bugs Tracking Issue

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#15]

**Comment by writerly03** [comment]
- [ ] Monument pop-ups close immediately on click much of the time
- [ ] Search box on map doesn't close

**Comment by writerly03** [comment]
@tripledoublev here's the recording of the popups closing. I think this is likely because my screen is so small. But the net effect is that a lot of the popups close immediately and it makes for a frustrating user experience

**Comment by writerly03** [comment]
- [ ] Sort out pop-up/headline collision

**Comment by tripledoublev** [comment]
#117 for now, if popup opens, headline fades away. 

in the future,
this could be improved with a more sophisticated mechanism that keeps track of the popup position and then only hides the header if there is overlap.

 the current implementation will hide the header no matter where the popup is. it does prevent collisions but is 'overkill' as some of these popups do not necessarily interfere with the H1

**Comment by tripledoublev** [comment]
I am tempted to close this issue but of course other bugs will need my attention in the future...
@writerly03, let me know if you want to keep this issue opened for future bug tracking or if we close simply close it for now

**Comment by writerly03** [comment]
Closed; can open a new tracking issue once this phase is wrapped
